name = "cloudflare-rust-kv-example"
type = "javascript"
workers_dev = true
compatibility_date = "2021-10-07"
compatibility_flags = [ "formdata_parser_supports_files" ] # required

[vars]
WORKERS_RS_VERSION = "0.0.6"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"


kv_namespaces = [ 
  { binding = "KV_TEST_NS", id = "0f2bad10127f46f0b8466d9ac37332a4" }
]

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
